# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\yelts\OneDrive\Escritorio\Proyecto_A (2)\Proyecto_A\UI\ventanaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(625, 185)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 10, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnSalir = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalir.setGeometry(QtCore.QRect(160, 80, 281, 37))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnSalir.setFont(font)
        self.btnSalir.setObjectName("btnSalir")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 625, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuRegistro = QtWidgets.QMenu(self.menuBar)
        self.menuRegistro.setObjectName("menuRegistro")
        self.menuComprobantes = QtWidgets.QMenu(self.menuBar)
        self.menuComprobantes.setObjectName("menuComprobantes")
        MainWindow.setMenuBar(self.menuBar)
        self.actionClientes = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\yelts\\OneDrive\\Escritorio\\Proyecto_A (2)\\Proyecto_A\\UI\\../Iconos/MISC28.ICO"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClientes.setIcon(icon)
        self.actionClientes.setObjectName("actionClientes")
        self.actionEmpleados = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\yelts\\OneDrive\\Escritorio\\Proyecto_A (2)\\Proyecto_A\\UI\\../Iconos/Empleado.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEmpleados.setIcon(icon1)
        self.actionEmpleados.setObjectName("actionEmpleados")
        self.actionProductos = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\yelts\\OneDrive\\Escritorio\\Proyecto_A (2)\\Proyecto_A\\UI\\../Iconos/EXPDYMAP.ICO"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProductos.setIcon(icon2)
        self.actionProductos.setObjectName("actionProductos")
        self.actionVista_Previa = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\yelts\\OneDrive\\Escritorio\\Proyecto_A (2)\\Proyecto_A\\UI\\../Iconos/NOTE14.ICO"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVista_Previa.setIcon(icon3)
        self.actionVista_Previa.setObjectName("actionVista_Previa")
        self.actionProveedor = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\yelts\\OneDrive\\Escritorio\\Proyecto_A (2)\\Proyecto_A\\UI\\../Iconos/folder users.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProveedor.setIcon(icon4)
        self.actionProveedor.setObjectName("actionProveedor")
        self.menuRegistro.addAction(self.actionClientes)
        self.menuRegistro.addAction(self.actionEmpleados)
        self.menuRegistro.addAction(self.actionProductos)
        self.menuRegistro.addAction(self.actionProveedor)
        self.menuComprobantes.addAction(self.actionVista_Previa)
        self.menuBar.addAction(self.menuRegistro.menuAction())
        self.menuBar.addAction(self.menuComprobantes.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Menu principal"))
        self.label.setText(_translate("MainWindow", "Menu Principal"))
        self.btnSalir.setText(_translate("MainWindow", "Cerrar"))
        self.menuRegistro.setTitle(_translate("MainWindow", "Registro"))
        self.menuComprobantes.setTitle(_translate("MainWindow", "Comprobantes"))
        self.actionClientes.setText(_translate("MainWindow", "Clientes"))
        self.actionClientes.setShortcut(_translate("MainWindow", "Alt+C"))
        self.actionEmpleados.setText(_translate("MainWindow", "Empleados"))
        self.actionEmpleados.setShortcut(_translate("MainWindow", "Alt+E"))
        self.actionProductos.setText(_translate("MainWindow", "Productos"))
        self.actionProductos.setShortcut(_translate("MainWindow", "Alt+P"))
        self.actionVista_Previa.setText(_translate("MainWindow", "Vista Previa"))
        self.actionVista_Previa.setShortcut(_translate("MainWindow", "Alt+V"))
        self.actionProveedor.setText(_translate("MainWindow", "Proveedor"))
        self.actionProveedor.setShortcut(_translate("MainWindow", "Alt+Q"))
